package com.pp.library_network.eyepetizer.bean.recommend

data class DataXXX(
    val ad: Boolean,
    val adTrack: List<Any>,
    val author: AuthorXX,
    val brandWebsiteInfo: Any,
    val campaign: Any,
    val category: String,
    val collected: Boolean,
    val consumption: Consumption,
//    val cover: CoverXX,
    val dataType: String,
    val date: Long,
    val description: String,
    val descriptionEditor: String,
    val descriptionPgc: String,
    val duration: Int,
    val favoriteAdTrack: Any,
    val id: Int,
    val idx: Int,
    val ifLimitVideo: Boolean,
    val label: Any,
    val labelList: List<Any>,
    val lastViewTime: Any,
    val library: String,
    val playInfo: List<PlayInfoX>,
    val playUrl: String,
    val played: Boolean,
    val playlists: Any,
    val promotion: Any,
//    val provider: ProviderX,
    val reallyCollected: Boolean,
    val recallSource: Any,
    val recall_source: Any,
    val releaseTime: Long,
    val remark: String,
    val resourceType: String,
    val searchWeight: Int,
    val shareAdTrack: Any,
    val slogan: String,
    val src: Any,
    val subtitles: List<Any>,
//    val tags: List<TagX>,
    val thumbPlayUrl: String,
    val title: String,
    val titlePgc: String,
    val type: String,
//    val videoPosterBean: VideoPosterBeanX,
    val waterMarks: Any,
    val webAdTrack: Any,
//    val webUrl: WebUrlX
)